### PR TITLE
when clicking on skip credits, skip to the next episode

### PR DESCRIPTION
**Pull request by dredstone1**
until now when i clicked on skip credit it skip to the end of the video and then i needed to click on next up, this fix that, so when i click on skip credits button it will just skip to the next episode.
this meant to mimic the behavior of the web-version

### CODE REVIEW

**Comment by jumoog** [comment]
should be a config in the client and default is `show button`

**Comment by dredstone1** [comment]
you mean to add the option to disable the skip to the next episode?
it will always show the button, this pr change it to skip to the next episode when you click on the skip credits.
it meant to mimic the behavior of the web-version

**Comment by jumoog** [comment]
ahh okay

**Comment by jumoog** [comment]
why do you closed it?

**Comment by dredstone1** [comment]
a mistake

**Pull request closed without merging**
